### ISSUE TITLE
Capture Git repository in a custom value

### ISSUE THREAD

**Issue by erichaagdev** [spring-io/develocity-conventions#85]
In Develocity 2024.1, the [Develocity Reporting and Visualization](https://gradle.com/develocity/releases/2024.1#create-arbitrary-reports-and-visualizations-of-develocity-build-data) feature was released. This enables users to build custom reports and dashboards to better visualize and analyze build data. To help users get started, a set of preconfigured dashboards are offered. The majority of these preconfigured dashboards rely only on the data provided by build scans out-of-the-box, but a subset of them assume build scans have specific tags and custom values. 

The full list of tags and custom values are documented [here](https://docs.gradle.com/develocity/reporting-kit/installation-manual/current/#2_build_environment). The only data not currently captured by this plugin is the `Git repository` of the project being built as a custom value.

An example of adding the `Git repository` custom value can be seen in the Common Custom User Data plugin [for Gradle](https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/cd5bdb3bec750005824e5686500c5e86727ddd3a/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L424) and extension [for Maven](https://github.com/gradle/common-custom-user-data-maven-extension/blob/59ef29dd8e7ccf777b31a86f635ec67e8d19bf6e/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L370).

**Comment by wilkinsona** [comment]
Thanks for the suggestion but I'm not sure we can do this for similar reasons to https://github.com/spring-io/develocity-conventions/issues/42#issuecomment-2109731669. For local builds at least, there's no guarantee that the `origin` remote will be the one to use. For example, I believe that some members of the Spring team have their own fork as `origin` and then have the "primary" repository as a remote named `upstream`.

**Comment by erichaagdev** [comment]
In the case of the Develocity Reporting and Visualization preconfigured dashboards, only the base repository name is considered. So both `git@github.com:erichaagdev/spring-boot` and `git@github.com:wilkinsona/spring-boot` will report as `spring-boot`. This won't work if the fork is called `erichaagdev/my-spring-boot-fork`, but it's typically good enough to handle most cases and better than it not reporting at all.

**Comment by wilkinsona** [comment]
If only the base repository name is used what's the benefit of the git information versus the name of the root project that's already captured in a build scan? The root project name would appear to convey the same level of information while having the benefit that it won't change if someone names a fork unusually.

**Comment by erichaagdev** [comment]
You bring up a valid point. This can be useful when you have more than one build in a single repository, but I understand this scenario may not apply to you. In which case, please feel free to close the issue.

More generally, it can be useful in automation scenarios where the Git repository is required to do additional processing, but again that use case may not apply.

**Comment by wilkinsona** [comment]
Right now, I don't think this applies to the various Spring projects. I'll close it for now but we can reconsider in the future should a need arise.
